### ISSUE TITLE
ProxyCommand is ignored with network_cli connection

### ISSUE THREAD

**Issue by demiph** [ansible-collections/ansible.netcommon#296]
##### SUMMARY

Using the --ssh-common-args option does not work when using the network_cli connection type. Instead of using the bastion host specified, a direct connection is attempted to the proxied host
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.netcommon.network_cli
##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1]
  config file = None
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/username/Library/Python/3.8/lib/python/site-packages/ansible
  ansible collection location = /Users/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/username/Library/Python/3.8/bin/ansible
  python version = 3.8.2 (default, Aug 25 2020, 09:23:57) [Clang 12.0.0 (clang-1200.0.32.2)]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION

```paste below
No changes here
```

##### STEPS TO REPRODUCE

Install core 2.11.1
Install collection cisco.nxos, ansible.netcommon

```yaml
[switch]
192.168.50.10 ansible_network_os=cisco.nxos.nxos
```
```
ansible all -i ./hosts -c network_cli -u test -k -m nxos_command -a "commands='show run'" -e ansible_network_os=nxos --ssh-common-args '-o ProxyCommand="ssh -W %h:%p -q test@192.168.50.5"'
```

##### EXPECTED RESULTS

I am expecting to see a connection to the bastion host

##### ACTUAL RESULTS

A tcpdump shows that a connection to the proxied host instead of the bastion host

```paste below
10:12:13.074389 IP 192.168.100.1.61142 > 192.168.50.10.ssh: Flags [S], seq 1545228954, win 65535, options [mss 1350,nop,wscale 6,nop,nop,TS val 1054185853 ecr 0,sackOK,eol], length 0
10:12:14.082349 IP 192.168.100.1.61142 > 192.168.50.10.ssh: Flags [S], seq 1545228954, win 65535, options [mss 1350,nop,wscale 6,nop,nop,TS val 1054186853 ecr 0,sackOK,eol], length 0
10:12:15.101765 IP 192.168.100.1.61142 > 192.168.50.10.ssh: Flags [S], seq 1545228954, win 65535, options [mss 1350,nop,wscale 6,nop,nop,TS val 1054187853 ecr 0,sackOK,eol], length 0
10:12:17.127047 IP 192.168.100.1.61142 > 192.168.50.10.ssh: Flags [S], seq 1545228954, win 65535, options [mss 1350,nop,wscale 6,nop,nop,TS val 1054189853 ecr 0,sackOK,eol], length 0
10:12:21.248321 IP 192.168.100.1.61142 > 192.168.50.10.ssh: Flags [S], seq 1545228954, win 65535, options [mss 1350,nop,wscale 6,nop,nop,TS val 1054193853 ecr 0,sackOK,eol], length 0
```

**Comment by NilashishC** [comment]
@demiph This is likely an issue starting from ansible-core 2.11. As a workaround, you can either use the `proxy_command` ini entry under `paramiko_connection` section in ansible.cfg or use the environment variable `ANSIBLE_PARAMIKO_PROXY_COMMAND`.

**Comment by demiph** [comment]
Using the proxy_command entry in ansible.cfg does not work either.  An attempt to run ```ansible-config dump --only-changed``` does not show this changed configuration either. I am thinking this particular entry is not recognized at all

**Comment by NilashishC** [comment]
@demiph Both the environment variable and the ansible.cfg option work fine for me with ansible-core 2.11. Also, I don't think `ansible-config dump --only-changed` will reflect this change. Here's the settings I used:

ansible.cfg:
```
[defaults]
inventory=$HOME/ansible_inventory/inventory

[persistent_connection]
command_timeout = 3000
connect_timeout = 60
connect_retry_timeout = 500

[paramiko_connection]
proxy_command = 'ssh -i ~/jumphost_1.pem -W %h:%p -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null fedora@a.b.c.d'
```
OR

```
export ANSIBLE_PARAMIKO_PROXY_COMMAND='ssh -i ~/jumphost_1.pem -W %h:%p -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null fedora@a.b.c.d'
 ```

Alternatively, you can switch to Ansible 2.9.22 which should have `ansible_ssh_common_args` working.

**Comment by demiph** [comment]
I can confirm the workaround is good, but we will just wait till it is fixed in 2.11

**Comment by craigers521** [comment]
I think someone already mentioned this somewhere but the problem with the workaround is its turned on for every host target in your inventory, whereas using ansible_ssh_common_args you can define a unique proxy per host/group.  So for situations like say a PCI or DMZ zone where maybe your insane security team has different jump servers for different environments this kind of breaks that. Just wanted to keep this thread alive, looking forward to a fix for 2.11.

**Comment by empusas** [comment]
I can confirm that issue still exists in 2.12.2, but the work around is working. But this took me days to find. After a system upgrade all my playbooks stopped working because of this.

ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True

**Comment by Blorpy** [comment]
Looks like this is still broken in 2.12.6. I agree the workaround is pretty limited, its a valid scenario where different groups of hosts might need to use different jump hosts.

**Comment by sc68cal** [comment]
I also have this issue, where I need to set `proxy_command` in a `group_var` file, since there's only a small subset of hosts using `network_cli` and `paramiko` where a bastion is needed. It would be useful to be able to set it in the group_var file instead of having to set `ANSIBLE_PARAMIKO_PROXY_COMMAND` in the shell, since that forces us to run two ansible-playbook CLI commands differently

**Comment by rlangus** [comment]
As a work around, I removed host lines with "ssh-rsa" in my controller's known_hosts file, and the problem went away.

**Comment by markatdxb** [comment]
Is there any ETA to get this fixed permanently ? This basically leaves us only with netcommon_cli using paramiko when connecting via jump host. Or is there any other alternative ?

**Comment by Qalthos** [comment]
This is now fixed in ansible-core and will be released with 2.14. Backports to [2.13](https://github.com/ansible/ansible/pull/78590) and [2.12](https://github.com/ansible/ansible/pull/78591) are open. If you are still having trouble with the implementation as it exists in ansible-core devel, please open a new issue to outline your problem.

Thanks!

**Comment by cwiech** [comment]
This still appears to be broken in  2.14.0.dev0. I tried to open a new issue, but the bot auto-closed it.

**Comment by gburjan** [comment]
I experience the same as @cwiech after upgrade to Ansible 6.4 (ansible-core 2.13.4) - which should have this fix based on the changelog.

After the upgrade, ansible.netcommon still used paramiko, and it is still broken, ProxyCommand defined in ansible_ssh_common_args is still ignored.

The good news is that based on a fallback warning "[WARNING]: ansible-pylibssh not installed, falling back to paramiko" I decided to install "ansible-pylibssh".  After that ansible.netcommon started using it instead of paramiko and with that this problem doesn't happen.
